new_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nz_health.urls')),
    path('', include('django.contrib.auth.urls')),
]


# login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

nz_health/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('person', views.person, name='person_list'),
    path('person/<int:id>', views.person_form, name="person_update"),
    path('delete/<int:id>', views.person_delete, name="person_delete"),
    path('details/<int:id>', views.person_details, name="person_details"),
    path('details/<int:person_id>/add_referral', views.add_referral, name="add_referral"),
    path('person_form', views.person_form, name='person_form'),

    path('referrals', views.referrals, name='referral_list'),

    path('referrals/<int:id>', views.referral_form, name="referral_update"),
    path('referral_delete/<int:id>', views.referral_delete, name="referral_delete"),
    path('referral-details/<int:id>', views.referral_details, name="referral_details"),
    path('referral_form', views.referral_form, name='referral_form'),

    # path('position', views.position, name='position'),
    # path('position/<int:id>', views.position_form, name="position_update"),
    # path('position/<int:id>', views.position_delete, name="position_delete"),
    # path('position_form', views.position_form, name='position_form'),

]

nz_health/models.py
from django.db import models

# Create your models here.


class Person(models.Model): 
    first_name = models.CharField("First Name", max_length=40, blank=True, null=True)
    last_name = models.CharField("Last Name", max_length=40, blank=True, null=True)
    date_of_birth = models.DateField("Date", max_length=8)
    
    class Meta:  
        db_table = "Person"

    def __str__(self):
        return self.first_name + ', ' + self.last_name
        


class Referral(models.Model):
    referrer = models.CharField("Referrer", max_length=40)
    referral_date = models.DateField("Referral Date", max_length=8)
    note = models.TextField("Text")
    person = models.ForeignKey(Person, on_delete=models.CASCADE);
    
    class Meta:  
        db_table = "Referral"  

    # def __str__(self):
    #     return self.referrer




        


    

nz_health/forms.py
from django import forms
from django.db import models
from django.db.models.base import Model
from django.forms import fields, widgets
from .models import Person, Referral


class DateInput(forms.DateInput):
    input_type = 'date'


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = "__all__"

        widgets = {'date_of_birth': DateInput()}

        labels = {
            'date_of_birth': 'Date Of Birth'
        }

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].empty_label = "Select"


class ReferralForm(forms.ModelForm):
    class Meta:
        model = Referral
        fields = ['referrer', 'referral_date', 'note']
        widgets = {'referral_date': DateInput()}
        labels = {
            'referrer': 'Referrer',
            'referral_date': 'Referral Date',
            'note': 'Note'
        }


class AddReferralForm(forms.ModelForm):
    class Meta:
        model = Referral
        fields = '__all__'
        widgets = {'referral_date': DateInput()}
        labels = {
            'referrer': 'Referrer',
            'referral_date': 'Referral Date',
            'note': 'Note'
        }

nz_health/views.py
from .models import Person,  Referral
from django.shortcuts import redirect, render
from .forms import PersonForm,  ReferralForm, AddReferralForm
from django.contrib.auth.decorators import login_required

from nz_health import forms

# Create your views here.
# Home to render general info

def home (request):
    return render(request, "nz_health/home.html");



#Person
@login_required(login_url='/login')
def person (request):
    person = Person.objects.all()
    return render(request, "nz_health/person.html", {"person":person});
@login_required
def person_details (request, id):   
    person_details = Person.objects.get(pk = id)
    referral_form = ReferralForm()
    return render(request, "nz_health/person_details.html", 
        {
            "person_details":person_details,
            "referral_form":referral_form,
        });
# POST and GET request
# Create new person or get the list of person
@login_required(login_url='/login')
def person_form (request, id=0):
    #POST request
    if request.method == 'POST':
        #Create new Person
        if id == 0:
            person_form = PersonForm(request.POST)
        #Update/Edit Person
        else:
            person = Person.objects.get(pk=id)
            person_form = PersonForm(request.POST, instance=person)
        if person_form.is_valid():
            person_form.save()
        return redirect('/person')
    #GET request       
    else:
        if id == 0:
            person_form = PersonForm()
        #GET a Person
        else:
            person = Person.objects.get(pk=id)
            person_form = PersonForm(instance=person)
    return render(request, 'nz_health/person_form.html',{'person_form': person_form})

@login_required(login_url='/login')
def person_delete (request, id):
    person_delete = Person.objects.get(id=id)
    if request.method == "POST":
        person = Person.objects.get(pk=id)
        person.delete()
        return redirect('/person')
    return render(request, "nz_health/person_delete.html", {"person_delete":person_delete});
#Referrals

@login_required(login_url='/login')
def referrals (request):
    referrals = Referral.objects.all()
    return render(request, "nz_health/referrals.html", {"referrals":referrals});


# def referral_form (request):
   # return render(request, "nz_health_app/referral_form.html");

@login_required(login_url='/login')
def referral_form (request, id=0):
    if request.method == 'POST':
        if id == 0:
            referral_form = AddReferralForm(request.POST)
        else:
            referrals = Referral.objects.get(pk=id)
            referral_form = AddReferralForm(request.POST, instance=referrals)
        if referral_form.is_valid():
            referral_form.save()
        return redirect('/referrals')       
    else:
        if id == 0:
            referral_form = AddReferralForm()
        else:
            referrals = Referral.objects.get(pk=id)
            referral_form = AddReferralForm(instance=referrals)
    return render(request, 'nz_health/referral_form.html',{'referral_form': referral_form})


@login_required(login_url='/login')
def referral_delete (request, id):
    referral_delete = Referral.objects.get(id=id)
    if request.method == "POST":
        referral_delete.delete()
        return redirect('/referrals')
    return render(request, "nz_health/referral_delete.html", {"referral_delete":referral_delete});

@login_required(login_url='/login')
def referral_details (request, id):   
    referral_details = Referral.objects.filter(pk=id)
    return render(request, "nz_health/referral_details.html", {"referral_details":referral_details});

@login_required(login_url='/login')
def add_referral (request, person_id):
    # Create ModelForm using the data in the request.POST
    form = ReferralForm(request.POST)
    #validate the form
    if form.is_valid():
        new_referral = form.save(commit=False)
        new_referral.person_id = person_id
        new_referral.save()
    return redirect('person_details', id=person_id)
    

nz_health/templates/nz_health/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>NZ Health</title>
  </head>
  <body>
    <header>
      <img id="logo" src="/static/logo.png" />
    </header>
    <nav>
      <ul id="topnav">
        <li><a href="/">Home</a></li>
        <li><a href="/person">Person</a></li>
        <li><a href="/referrals">Referral</a></li>
        {% if user.is_authenticated %}
        <li><a class="login" href="/logout">Logout</a></li>
        {% else %}
        <li><a class="login" href="/login">Login</a></li>
        {% endif %}
      </ul>
    </nav>

    <main>{% block content %} {% endblock content %}</main>
    <footer>
      <div id="botnav">
        <p>&copy; NZ Health, 2021</p>
      </div>
    </footer>
  </body>
</html>

nz_health/templates/nz_health/home.html
{% extends "nz_health/base.html" %} 
{% block content %} 
  {% if user.is_authenticated %}
    <div>
      <h3>
        Welcome {{ user|capfirst }}
      </h3>
      <h3>
        Have a great working day!
      </h3>
    </div>
    <img class="home-img" src="/static/case.png" />
    <aside id="homecontent">
      <button class="btn person-list">
        <a href="/person">View Person List</a>
      </button>
      <button class="btn add-person">
        <a href="/person_form">Add New Person</a>
      </button>
      <button class="btn referrer-list">
        <a href="/referrals">View Referrals</a>
      </button>
      <button class="btn referral">
        <a href="/referral_form">Add Referral</a>
      </button>
      <button class="btn admin">
        <a href="/admin">Admin</a>
      </button>
    </aside>
  {% else %}
    <div>
      <h3 class="welcome">
        Welcome to Health Management Case System
      <h3>
      <p>Please <a class='login-home' href="/login">Login</a> to start the section</p>
      <img class="home-img" src="/static/case.png" />
    </div>
  {% endif %} 

{% endblock content %}
  

nz_health/templates/nz_health/person.html
{% extends "nz_health/base.html" %} {% block content %}
<h2>PERSON LISTING</h2>
<div>
  <button class="btn add-person">
    <a href="/person_form">Add New Person</a>
  </button>
<div>
<table>
  <tr>
    <th>Person ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Action</th>
  </tr>
  {% for the_person in person %}
  <tr>
    <td>{{ the_person.id }}</td>
    <td>{{ the_person.first_name }}</td>
    <td>{{ the_person.last_name }}</td>
    <td class="action">
      <button class="button details">
        <a href="{% url 'person_details' the_person.id %}">Add Referrer</a>
      </button>
      <button class="button details">
        <a href="{% url 'person_details' the_person.id %}">Details</a>
      </button>

      <button class="button edit">
        <a href=" {% url 'person_update' the_person.id %}">Edit</a>
      </button>

      <button class="button delete">
        <a href=" {% url 'person_delete' the_person.id %}">Delete</a>
      </button>
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

nz_health/templates/nz_health/person_delete.html
{% extends "nz_health/base.html" %} {% block content %}
<h3>Confirm Delete</h3>

<h4>Are you sure you want to delete {{ person_delete }} ?</h4>

<form id='confirm-delete' action="{% url 'person_delete' person_delete.id %}" method="POST">
  {% csrf_token %}
  <button><a href="/person">Cancel</a></button>
  <button class='confirm-delete' type="submit" name="Confirm">DELETE</button>
</form>

{% endblock content %}

nz_health/templates/nz_health/person_details.html
{% extends "nz_health/base.html" %} {% block content %}
<h3>Person Details</h3>

<div id='details-display'>

      <form
        action="{% url 'add_referral' person_details.id %}"
        method="post"
        autocomplete="off"
        
      >
        {% csrf_token %} 
        
        

        <table id="referral_form">
        <tr>
          <td>
            <button class="btn back">
              <a href="/person">Back</a>
            </button>
          </td>    
        </tr>
        <tr>
          <td><strong>First Name: {{ person_details.first_name }}</strong></td>    
        </tr>
        <tr>
          <td><strong>Last Name: {{ person_details.last_name }}</strong></td>    
        </tr>
        <tr>
          <td><strong>Date of Birth:    {{ person_details.date_of_birth }}</strong></td>    
        </tr>      
        <tr>
          <td>{{ referral_form.referrer.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.referrer }}</td>
        </tr>
        <tr>
          <td>{{ person_form.referrel_date.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.referral_date }}</td>
        </tr>
        <tr>
          <td>{{ referral_form.note.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.note }}</td>
        </tr>
      
        
        <tr>
          <td>
            <input type="submit" value="Submit" class="btn submit"/>
            
          </td>  
        </tr>
        
      </table> 

      </form>
    
  
  <table class='person-details'>
    <tr>
      <th>Referrer</th>
      <th>Referrer Date</th>
      <th>Note</th>
    </tr>
    {% for referral in person_details.referral_set.all %}
    <tr>
      <td>{{ referral.referrer }}</td>

      <td>{{ referral.referral_date}}</td>
      <td>{{ referral.note }}</td>
    </tr>
    {% endfor%}
  </table>
</div>



{% endblock content %}

nz_health/templates/nz_health/person_form.html
{% extends "nz_health/base.html" %}
 {% comment %} Comment {% endcomment %}
 
{% block content %}
    
    <h3>ADD NEW PERSON</h3>
    
    <form method="post" autocomplete="off" >
        {% csrf_token %}
        
        {% comment %} {{ person_form }} {% endcomment %}
        
        <table id="person_form">
        <tr>
          <td><button class='btn back'>
        <a type="button" href="{% url 'person_list' %}">Back to List</a>
        </button></td>    
        </tr>
        <tr>
          <td>{{ person_form.first_name.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ person_form.first_name }}</td>
        </tr>
        <tr>
          <td>{{ person_form.last_name.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ person_form.last_name }}</td>
        </tr>
        <tr>
          <td>{{ person_form.date_of_birth.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ person_form.date_of_birth }}</td>
        </tr>
        
        <tr>
          <td>
            <input type="submit" value="Submit" class="btn submit"/>
            
          </td>  
        </tr>
        
      </table> 
       
    </form>
  

{% endblock content %}

nz_health/templates/nz_health/referral_delete.html
{% extends "nz_health/base.html" %} {% block content %}
<h3>Confirm Delete</h3>

<h4>Are you sure you want to delete {{ referral_delete.referrer }} ?</h4>

<form id='confirm-delete' action="{% url 'referral_delete' referral_delete.id %}" method="POST">
  {% csrf_token %}
  <button><a href="/referrals">Cancel</a></button>
  <button class='confirm-delete' type="submit" name="Confirm">DELETE</button>
</form>

{% endblock content %}

nz_health/templates/nz_health/referral_details.html
{% extends "nz_health/base.html" %} {% block content %}
<h3>Referral Details</h3>
<button class="btn back referral">
  <a href="/referrals">Back</a>
</button>
<table>
  <tr>
    <th>ID</th>
    <th>Referrer</th>
    <th>Patient First_Name</th>
    <th>Patient Last_Name</th>
    <th>Patient DOB</th>
    <th>Referral Date</th>
    <th>Note</th>
  </tr>
  {% for referral in referral_details %}

  <tr>
    <td>{{ referral.id }}</td>
    <td>{{ referral.referrer}}</td>
    <td>{{ referral.person.first_name }}</td>
    <td>{{ referral.person.last_name }}</td>
    <td>{{ referral.person.date_of_birth }}</td>
    <td>{{ referral.referral_date}}</td>
    <td>{{ referral.note}}</td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

nz_health/templates/nz_health/referral_form.html
{% extends "nz_health/base.html" %}
 {% comment %} Comment {% endcomment %}
{% block content %}
    <h3>ADD NEW REFERRAL</h3>
    
    <form method="post" autocomplete="off" id="referral_form">
        {% csrf_token %}
        
        {% comment %} {{ referral_form }} {% endcomment %}

        <table id="referral_form">
        <tr>
          <td><button class='btn back'>
        <a type="button" href="{% url 'referral_list' %}">Back to Referrals</a>
        </button></td>    
        </tr>
        <tr>
          <td>{{ referral_form.referrer.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.referrer }}</td>
        </tr>
        <tr>
          <td>{{ person_form.referrel_date.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.referral_date }}</td>
        </tr>
        <tr>
          <td>{{ referral_form.note.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.note }}</td>
        </tr>
        <tr>
          <td>{{ referral_form.person.label_tag }}</td>    
        </tr>
        <tr>
          <td>{{ referral_form.person }}</td>
        </tr>
        
        <tr>
          <td>
            <input type="submit" value="Submit" class="btn submit"/>
            
          </td>  
        </tr>
        
      </table> 
        
        {% comment %} <div>
        <button class='btn submit' type="submit" >Submit</button>
        
        </div> {% endcomment %}
    </form>
    

{% endblock content %}

nz_health/templates/nz_health/referrals.html
{% extends "nz_health/base.html" %} {% block content %}
<h3>Referrals List</h3>

<button class="btn add-referral">
  <a href="/referral_form">Add New Referral</a>
</button>
<table>
  <tr>
    <th>ID</th>
    <th>Referrer</th>
    <th>Patient First_Name</th>
    <th>Patient Last_Name</th>

    <th>Referral Date</th>
    <th>Action</th>
  </tr>
  {% for referral in referrals %}

  <tr>
    <td>{{ referral.id }}</td>
    <td>{{ referral.referrer}}</td>
    <td>{{ referral.person.first_name }}</td>
    <td>{{ referral.person.last_name }}</td>

    <td>{{ referral.referral_date}}</td>
    <td>
      <button class="button details">
        <a href="{% url 'referral_details' referral.id %}">Details</a>
      </button>

      <button class="button edit">
        <a href=" {% url 'referral_update' referral.id %}">Edit</a>
      </button>
      <button class="button delete">
        <a href=" {% url 'referral_delete' referral.id %}">Delete</a>
      </button>
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}